# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/enterprise-server@3.9/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Amsterdam
    assignees:
      - kaylumah
    groups:
      Microsoft:
        patterns:
          - Microsoft.Extensions.*
          - System.*
        exclude-patterns:
          - System.IO.Abstractions
          - System.IO.Abstractions.*
      AzureFunction:
        patterns:
          - Microsoft.Azure.Functions.*
      System.IO.Abstractions:
        patterns:
          - System.IO.Abstractions
          - System.IO.Abstractions.*
      Xunit:
        patterns:
          - xunit.runner.visualstudio
          - xunit
      Verify:
        patterns:
          - Verify.XunitV3
          - Verify.Xunit
    open-pull-requests-limit: 25

  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    ignore:
      - dependency-name: "*"
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: npm
    # directory: /
    directories:
      - /
      - blog-api/
    schedule:
      interval: daily
      time: '09:00'
      timezone: Europe/Amsterdam
    # ignore:
    #   - dependency-name: "axios"
    #   - dependency-name: "tar-fs"
    assignees:
      - kaylumah
    groups:
      tailwind:
        patterns:
          - '@tailwindcss/*'
          - tailwindcss

  - package-ecosystem: github-actions
    directory: /
    assignees:
      - kaylumah
    schedule:
      interval: weekly
      time: '09:00'
      timezone: Europe/Amsterdam
