# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-azure/deploying-to-azure-static-web-app 
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig

name: Kaylumah.nl CI/CD

env:
  APP_LOCATION: "dist" # App source code path
  API_LOCATION: "" # Api source code path - optional
  OUTPUT_LOCATION: "" # Built app content directory - optional

on:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
        - main

# permissions:
#   issues: write
#   contents: read
#   pull-requests: write

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set TimeZone
        uses: hoang-rio/set-timezone@v1.4
        with:
          timezoneLinux: "Europe/Amsterdam"
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: 'Make tools available'
        shell: pwsh
        run: |
          dotnet tool restore
      - name: 'Generate Website'
        shell: pwsh
        run: |
          ./build.ps1 -BuildId $env:GITHUB_RUN_ID -BuildNumber $env:GITHUB_RUN_NUMBER -CleanDevDependencies
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
          action: "close"

# jobs:
#   build_and_deploy_job:
#     name: Build and Deploy Job
#     runs-on: ubuntu-20.04
#     outputs:
#       docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
#       # && github.event_name != 'pull_request'
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           # submodules: true
#           fetch-depth: 2
#       - name: 'Check if _site has changes'
#         id: check_file_changed
#         # if: github.event_name != 'pull_request'
#         shell: pwsh
#         run: |
#           $diff = git diff --name-only HEAD^ HEAD
#           $diff
#           $SiteFolderDiff = $diff | Where-Object { $_ -match '^_site/' }
#           $HasSite = $SiteFolderDiff.Length -gt 0
#           $SnapshotsFolderDiff = $diff | Where-Object { $_ -match '^test/E2e/Snapshots/' }
#           $HasSnapshots = $SnapshotsFolderDiff.Length -gt 0
#           Write-Host "SiteFolderDiff: $HasSite"
#           Write-Host "SnapshotsFolderDiff: $HasSnapshots"
#           # $SourceDiff = $diff | Where-Object { $_ -match '^_site/' -or $_ -match '^test/E2e/Snapshots/' }
#           # $HasDiff = $SourceDiff.Length -gt 0
#           $HasDiff = $HasSite -or $HasSnapshots
#           Write-Host "HasDiff: $HasDiff"
#           # Write-Host "::set-output name=docs_changed::$HasDiff"
#           echo "docs_changed=$HasDiff" >> $env:GITHUB_OUTPUT

#       - name: Sets env vars for PR
#         if: github.event_name == 'pull_request'
#         run: |
#           echo "PR_BUILD_ID=${{ github.event.number }}" >> $GITHUB_ENV

#       - name: Build And Deploy
#         if: github.actor != 'dependabot[bot]'
#         id: builddeploy
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
#           action: "upload"
#           ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
#           # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
#           app_location: "dist" # App source code path
#           api_location: "" # Api source code path - optional
#           output_location: "" # Built app content directory - optional
#           ###### End of Repository/Build Configurations ######
#       - name: 'Run E2E (PR)'
#         if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
#         run: |
#            pwsh ./test/E2e/bin/Release/net8.0/playwright.ps1 install chromium --with-deps
#            dotnet test test/E2e
#         env:
#           PLAYWRIGHT_TEST_BASE_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}
#       - name: 'Run E2E'
#         if: github.event_name != 'pull_request'
#         run: |
#            pwsh ./test/E2e/bin/Release/net8.0/playwright.ps1 install chromium --with-deps
#            dotnet test test/E2e
#         env:
#           PLAYWRIGHT_TEST_BASE_URL: https://kaylumah.nl
#       - name: Upload Test Results
#         if: failure()
#         uses: actions/upload-artifact@v4
#         with:
#           name: verify-test-results
#           path: |
#             **/*.received.*
#             **/*.verified.*

#   seo_job:
#     needs: [ build_and_deploy_job ]
#     if: needs.build_and_deploy_job.outputs.docs_changed && github.event_name != 'pull_request'
#     uses: ./.github/workflows/seo.yml

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.actor != 'dependabot[bot]'
#     runs-on: ubuntu-20.04
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         id: closepullrequest
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
#           action: "close"
