name: Kaylumah.nl CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#     runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'For Dependabot'
        if: github.actor == 'dependabot[bot]'
        shell: pwsh
        run: |
          Write-Output "PR created by Dependabot"
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Set TimeZone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Amsterdam"
      - name: Sets env vars for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_BUILD_ID=${{ github.event.number }}" >> $GITHUB_ENV
      - name: 'Make tools available'
        shell: pwsh
        run: |
          dotnet tool restore
      - name: 'Generate Website'
        shell: pwsh
        run: |
          ./build.ps1 -BuildId $env:GITHUB_RUN_ID -BuildNumber $env:GITHUB_RUN_NUMBER -CleanDevDependencies
      # disabled until https://github.com/SpecFlowOSS/SpecFlow/issues/2591
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: Test Reports
      #     path: ${{ github.workspace }}/LivingDoc.html
      - name: Build And Deploy
        if: github.actor != 'dependabot[bot]'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "dist" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      - name: 'Run E2E (PR)'
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: |
           pwsh ./test/E2e/bin/Release/net8.0/playwright.ps1 install chromium --with-deps
           dotnet test test/E2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.builddeploy.outputs.static_web_app_url }}
      - name: 'Run E2E'
        if: github.event_name != 'pull_request'
        run: |
           pwsh ./test/E2e/bin/Release/net8.0/playwright.ps1 install chromium --with-deps
           dotnet test test/E2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://kaylumah.nl
      - name: 'Verify Website'
        if: github.actor != 'dependabot[bot]'
        id: verifywebsite
        shell: pwsh
        run: |
          $SiteMapOutput = ./tools/Get-SiteMapUrls.ps1 -SiteMapUrl "${{ steps.builddeploy.outputs.static_web_app_url }}/sitemap.xml" | Foreach-object { $_.Trim() }
          $SiteMapOutputAsString = $SiteMapOutput -join ","
          echo "::set-output name=siteMapUrls::$SiteMapOutputAsString"
      # - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
      # - name: Lighthouse
      #   if: github.actor != 'dependabot[bot]'
      #   uses: foo-software/lighthouse-check-action@master
      #   with:
      #     outputDirectory: '${{ github.workspace }}/tmp/artifacts'
      #     urls: '${{ steps.verifywebsite.outputs.siteMapUrls }}'
      # - name: Upload artifacts
      #   if: github.actor != 'dependabot[bot]'
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: Lighthouse reports
      #     path: ${{ github.workspace }}/tmp/artifacts

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.actor != 'dependabot[bot]'
#     runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0353FEE03 }}
          action: "close"
