# - name: Test
#   run: dotnet test --no-restore --verbosity normal --logger trx test/Unit/Test.Unit.csproj
#   # run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

#  Enable the following to do something with snapshot result(s)
# - name: Check Verify Results
#   if: always()
#   run: |
#     $Output = & ./tools/Check-Snapshots.ps1
#     #  -TargetFolder Test/Unit
#     $Output = $Output | % { "." +$_ }
#     if ($Output.count -gt 0) {
#       New-Item -ItemType Directory "snapshots"
#       foreach ($File in $Output) {
#         Copy-Item $File -Destination snapshots
#       }
#     }
#   shell: pwsh

# - uses: actions/upload-artifact@v4
#   if: always()
#   with:
#     name: "snapshots-${{matrix.os}}"
#     path: snapshots
#     if-no-files-found: ignore
#     retention-days: 1