name: Upload SEO Data
on:
  workflow_call:
  workflow_dispatch:
  # push:
  #   branches: [ 'main' ]
  #   paths: [ '_site/**' ]

jobs:
  update_seo:
    name: Trigger SEO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 'Submit SiteMap URLs'
        shell: pwsh
        run: |
          ./tools/Seo.ps1 -BaseUrl "https://kaylumah.nl"
