name: Upload SEO Data
on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: [ '_site/**' ]

jobs:
  update_seo:
    name: Trigger SEO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Submit SiteMap URLs'
        shell: pwsh
        run: |
          ./tools/Seo.ps1 -BaseUrl "https://kaylumah.nl"
